### ISSUE TITLE
[BUG]: random UVB and LANGUAGE problems

### ISSUE THREAD

**Issue by The-Madhouse** [theyosh/TerrariumPI#481] opened 2020-11-18 20:30 UTC
Got a fresh install, i can't change thé username of password, because i have to select a language from thé drop down menu, but that menu is empty. 
Any idea's? 

Veml6075 sensor: connected correctly i guess. If i use the command to read i2c is see something connected to port 10(i guess? It's in row 0, and then line 10, and there it says 10. ) But when i try to add a sensor in terrarium pi menu and use adress ''10'' i don't get a reading.... 
What al i doing wrong?

**Comment by theyosh** [comment] 2020-12-03 00:17
Sorry for not responding earlier. But the language problem is new to me. I can only think of restarting my software, and clear your browser cache. Else we need more debug info.

And about the Veml6075. The address should be 10 . That is all. If there is no data, then there should be errors in either the screen session or in the logfiles in the log folder. https://github.com/theyosh/TerrariumPI/wiki/FAQ#how-to-debug-terrariumpi

**Comment by theyosh** [comment] 2020-12-09 20:07
Hi, do you still have an empty language list? I cannot reproduce.

**Comment by theyosh** [comment] 2020-12-16 21:53
Is this still an issue?

**Comment by theyosh** [comment] 2020-12-23 16:09
Any updates?

**Comment by theyosh** [comment] 2021-01-04 13:03
Closing due to no updates

**Closed by theyosh** 2021-01-04 13:03 UTC
