### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by Konrad84** [theyosh/TerrariumPI#736] opened 2022-09-22 19:45 UTC
- Raspberry PI: 3B

can´t get weather information over openweather 

Create Account and API 
Tried following Calls:

https://api.openweathermap.org/data/2.5/weather?q=Erding,DE&appid=[redacted]
https://api.openweathermap.org/data/2.5/weather?lat=44.34&lon=10.99&appid=[redacted]
![Weather Error](https://user-images.githubusercontent.com/104820070/191837244-2595d324-443e-43eb-84e1-511c68ef2a9d.JPG)

**Comment by theyosh** [comment] 2022-09-22 21:32
Hmm, I just tested with your weather url, but that does give an error. So I have to look into it.

Your first url is the correct one. That should work. I removed your appid value, as you should that keep secret ;)

**Comment by theyosh** [comment] 2022-09-22 21:50
Hmm, this is strange. I get a 401 error with your API key on a second call. That is something I cannot fix. What you can do is the following. You could try to generate a new API key in your account at Openweather. And then test the following two urls:

https://api.openweathermap.org/data/2.5/weather?q=Erding,DE&appid=[YOUR_NEW_API_KEY]
https://api.openweathermap.org/data/2.5/onecall?lat=48.306&lon=11.9069&units=metric&exclude=minutely&appid=[YOUR_NEW_API_KEY]&lang=nl

The first url is the url you enter in TP4. The second url is the url I construct to get more data. And the second url does give a 401 error with your old key. More info: https://openweathermap.org/faq#error401

But this is strange, as the first call is ok with your key, but the second is not. This is an issue at Openweather. So try to make a new key and see if that solves it. If not, you should contact Openweather why the first url is working, and the second is not.

Your free subscription plan is sufficient for all the online calls I do with TP4. So you should not have to have a paid plan.

I hope with a new API key it will work...

**Comment by Konrad84** [comment] 2022-10-02 17:55
Hi there,

 

thank you for your message! 

 

Not he new Key doesen´t work ether.

 

I get a error .. i wrote to openweather may they can give a hint.

 



 

Von: TheYOSH ***@***.***> 
Gesendet: Donnerstag, 22. September 2022 23:51
An: theyosh/TerrariumPI ***@***.***>
Cc: Konrad84 ***@***.***>; Author ***@***.***>
Betreff: Re: [theyosh/TerrariumPI] [BUG]: (Issue #736)

 

Hmm, this is strange. I get a 401 error with your API key on a second call. That is something I cannot fix. What you can do is the following. You could try to generate a new API key in your account at Openweather. And then test the following two urls:

https://api.openweathermap.org/data/2.5/weather?q=Erding,DE <https://api.openweathermap.org/data/2.5/weather?q=Erding,DE&appid=%5BYOUR_NEW_API_KEY%5D> &appid=[YOUR_NEW_API_KEY]
https://api.openweathermap.org/data/2.5/onecall?lat=48.306 <https://api.openweathermap.org/data/2.5/onecall?lat=48.306&lon=11.9069&units=metric&exclude=minutely&appid=%5BYOUR_NEW_API_KEY%5D&lang=nl> &lon=11.9069&units=metric&exclude=minutely&appid=[YOUR_NEW_API_KEY]&lang=nl

The first url is the url you enter in TP4. The second url is the url I construct to get more data. And the second url does give a 401 error with your old key. More info: https://openweathermap.org/faq#error401

But this is strange, as the first call is ok with your key, but the second is not. This is an issue at Openweather. So try to make a new key and see if that solves it. If not, you should contact Openweather why the first url is working, and the second is not.

Your free subscription plan is sufficient for all the online calls I do with TP4. So you should not have to have a paid plan.

I hope with a new API key it will work...

**Comment by STGMavrick** [comment] 2022-10-03 02:41
Hi  theyosh - I have the same issue as this guy. I sent you an email on 9/24 about it to the Gmail address listed.

**Comment by Konrad84** [comment] 2022-10-05 19:35
Hi there i sent a message to openweathermap and they answered that my api ist working fine they send me this:

 

Hello, thank you for contacting us.

Your API call works fine with no issues: https://api.openweathermap.org/data/2.5/weather?q=Erding,de <https://api.openweathermap.org/data/2.5/weather?q=Erding,de&APPID=de7a1fbd5f74afc83284ce53b8c9b504> &APPID=de7a1fbd5f74afc83284ce53b8c9b504

If you have any other questions, please don’t hesitate and contact us.

Kind regards,
Artūras Rosliakas
Technical Support Specialist

 

If i use the api URL in terrarium i get this Error

 



 

Von: ***@***.*** ***@***.***> 
Gesendet: Sonntag, 2. Oktober 2022 19:55
An: 'theyosh/TerrariumPI' ***@***.***>; 'theyosh/TerrariumPI' ***@***.***>
Cc: 'Author' ***@***.***>
Betreff: AW: [theyosh/TerrariumPI] [BUG]: (Issue #736)

 

Hi there,

 

thank you for your message! 

 

Not he new Key doesen´t work ether.

 

I get a error .. i wrote to openweather may they can give a hint.

 



 

Von: TheYOSH ***@***.*** ***@***.***> > 
Gesendet: Donnerstag, 22. September 2022 23:51
An: theyosh/TerrariumPI ***@***.*** ***@***.***> >
Cc: Konrad84 ***@***.*** ***@***.***> >; Author ***@***.*** ***@***.***> >
Betreff: Re: [theyosh/TerrariumPI] [BUG]: (Issue #736)

 

Hmm, this is strange. I get a 401 error with your API key on a second call. That is something I cannot fix. What you can do is the following. You could try to generate a new API key in your account at Openweather. And then test the following two urls:

https://api.openweathermap.org/data/2.5/weather?q=Erding,DE <https://api.openweathermap.org/data/2.5/weather?q=Erding,DE&appid=%5BYOUR_NEW_API_KEY%5D> &appid=[YOUR_NEW_API_KEY]
https://api.openweathermap.org/data/2.5/onecall?lat=48.306 <https://api.openweathermap.org/data/2.5/onecall?lat=48.306&lon=11.9069&units=metric&exclude=minutely&appid=%5BYOUR_NEW_API_KEY%5D&lang=nl> &lon=11.9069&units=metric&exclude=minutely&appid=[YOUR_NEW_API_KEY]&lang=nl

The first url is the url you enter in TP4. The second url is the url I construct to get more data. And the second url does give a 401 error with your old key. More info: https://openweathermap.org/faq#error401

But this is strange, as the first call is ok with your key, but the second is not. This is an issue at Openweather. So try to make a new key and see if that solves it. If not, you should contact Openweather why the first url is working, and the second is not.

Your free subscription plan is sufficient for all the online calls I do with TP4. So you should not have to have a paid plan.

I hope with a new API key it will work...

**Comment by theyosh** [comment] 2022-10-05 20:49
Hmm, it looks like they have changed there API pricing plans and therefore some urls. I need to investigate with them... :(

**Comment by theyosh** [comment] 2022-10-05 21:14
> Hi theyosh - I have the same issue as this guy. I sent you an email on 9/24 about it to the Gmail address listed.

Not sure where you mailed to, but I do not have a gmail address...

**Comment by STGMavrick** [comment] 2022-10-05 21:58
Sorry - not Gmail. It was to terrariumpi@theyosh.nl on 9/24.

**Comment by theyosh** [comment] 2022-10-07 20:41
Do a git pull and restart. It should work now for @Konrad84

For @STGMavrick you should change the url to: https://api.openweathermap.org/data/2.5/weather?q=Cincinnati,US&APPID=[YOUR_KEY]
Change is Cincinnati,OH,USA to Cincinnati,US

**Comment by STGMavrick** [comment] 2022-10-07 22:41
@theyosh Following your instructions I get the following. Just in case it was an appid issue I created another appid and I get the same result.

- 2022-10-07 18:38:32,725 - ERROR   - terrariumEngine       - Loading weather exception: 'appid'
2022-10-07 18:38:30,642 - INFO    - terrariumEngine       - Loading weather data from source https://api.openweathermap.org/data/2.5/weather?q=Cincinnati,US&APPID=34fe561b71f03364089c504440ce43fb

**Comment by theyosh** [comment] 2022-10-08 05:30
Totally my fault. Do another `git pull` and should be fixed. Sorry for the typo in code.

**Comment by STGMavrick** [comment] 2022-10-08 07:24
@theyosh That fixed it! Thank you!

**Comment by theyosh** [comment] 2022-10-08 07:29
There will be another update about getting more weather info. I think you should also subscribe for the One call api 3.0 in your account. But that needs entering a credit card :( I asked them about this, in order to see how I can still use their API.

Now you miss some forecast and the history data. But the basic data is there.

**Comment by Konrad84** [comment] 2022-10-08 08:34
Wow thank you a lot now it works !!!!

 

Hmm ok we´ll how long 😊

 

Nice !

 

Von: TheYOSH ***@***.***> 
Gesendet: Samstag, 8. Oktober 2022 09:29
An: theyosh/TerrariumPI ***@***.***>
Cc: Konrad84 ***@***.***>; Mention ***@***.***>
Betreff: Re: [theyosh/TerrariumPI] [BUG]: (Issue #736)

 

There will be another update about getting more weather info. I think you should also subscribe for the One call api 3.0 in your account. But that needs entering a credit card :( I asked them about this, in order to see how I can still use their API.

Now you miss some forecast and the history data. But the basic data is there.

**Comment by theyosh** [comment] 2022-10-08 13:17
Also updated information at the online help: https://theyosh.github.io/TerrariumPI/setup/#weather

**Comment by Konrad84** [comment] 2022-10-14 19:23
Hi There,

 

thanks for your help and sorry form y nooby questions.. i try to get camera started. 

 

I haver one IR Camera and dont get it working (Black Screen) and now i tried another one without IR and i get only Black screen. No Original Raspberry Pi cams .. is this a problem ? Should i chang somthing with the configuration?

 



 

Von: TheYOSH ***@***.***> 
Gesendet: Samstag, 8. Oktober 2022 15:18
An: theyosh/TerrariumPI ***@***.***>
Cc: Konrad84 ***@***.***>; Mention ***@***.***>
Betreff: Re: [theyosh/TerrariumPI] [BUG]: (Issue #736)

 

Also updated information at the online help: https://theyosh.github.io/TerrariumPI/setup/#weather

**Comment by theyosh** [comment] 2022-10-15 09:09
Change the white balance to auto? The white balance setting is mostly the cause of a black screen

**Comment by Konrad84** [comment] 2022-10-15 19:32
Thats it Genius ! 😊 Thank YOu

 

Von: TheYOSH ***@***.***> 
Gesendet: Samstag, 15. Oktober 2022 11:09
An: theyosh/TerrariumPI ***@***.***>
Cc: Konrad84 ***@***.***>; Mention ***@***.***>
Betreff: Re: [theyosh/TerrariumPI] [BUG]: (Issue #736)

 

Change the white balance to auto? The white balance setting is mostly the cause of a black screen

**Comment by Konrad84** [comment] 2022-10-16 12:49
Hopefully Last Question for now. What do you use foor connecting to the Turtle Pin threw the Internet? I got a Fritzbox. So you Connect via vpn? You got an advice Here?Am 15.10.2022 11:09 schrieb TheYOSH ***@***.***>:
Change the white balance to auto? The white balance setting is mostly the cause of a black screen

**Comment by theyosh** [comment] 2022-10-23 09:30
That is a bit outside the scope of TP4. But this should do it: https://www.edpnet.be/en/support/installation-and-usage/internet/manage-fritz!box/how-to-set-up-a-port-forwarding-on-a-fritzbox.html

It is called port forwarding. That means that everybody can find your TP4 setup online. It can take some time. but eventually it will be found. That is not a big problem, but you should know that.

Using VPN is a bit harder, and I cannot help you with that.

**Comment by theyosh** [comment] 2022-10-30 15:24
Closing as initial issue is fixed

**Closed by theyosh** 2022-10-30 15:24 UTC
