### ISSUE TITLE
How to add Mi temp BLE ?

### ISSUE THREAD

**Issue by captainboto** [theyosh/TerrariumPI#599] opened 2021-08-27 17:40 UTC
- TerrariumPI version: [4]
 - Raspberry PI: 4 / OS lite / Clean install

How to add mi temperature and humidity sensor it's not autodetected like Mi flora I try to scan and manual add but still fail 

![Screen Shot 2564-08-28 at 09 49 34](https://user-images.githubusercontent.com/74257775/131204163-dacfa631-4633-45f9-aa12-bf62e923b8ee.png)
![Screen Shot 2564-08-28 at 09 49 53](https://user-images.githubusercontent.com/74257775/131204161-0727c05d-a5d2-4f2a-9534-967920f0fcad.png)

**Comment by theyosh** [comment] 2021-08-30 09:09
Hi,
euh, maybe it is better to have an issue per problem. As this issue is now totally changed.

So, about the bluetooth, not sure why you have this issue. The easiest thing to to now is:
- stop terrariumpi `sudo service terrariumpi stop`
- remove the old database. `rm /home/pi/TerrariumPI/terrariumpi.db`
- run the installer once more: `sudo ./install.sh`
- reboot

If then there are no bluetooth sensors then I do not know why. Please open a new issue, where we can test the bluetooth. This will start with a new db, as you have some database issue as well. By removing the DB and start over is much easier.

About the mister, pleas use a different `type`! You should not use the lighting type for your mister. Please use humidity type for that. And you can press the question mark next to the title to get the information you need.
And the fields looks ok for what you want. 8 minutes of fog per hour for a hole day. But you should change it to a different type.

If you select the ignore option of a sensor/relay, it will be ignored in the hole system, and therefore not shown anywhere. To revert this, go to settings, and clear the ignored ids field.

For manual mode, just use the wrench icon and click again. But please not, that the data is cached, so the change could take about a 1 minute before you see it.

So, a lot of info, and I would rather see that you split this up in multiple issues. Else it gets complicated

**Comment by captainboto** [comment] 2021-08-30 12:56
ok, Thank you so much I will Create a new issue per problem.
So this issue will be bluetooth problem 

I try Clean install 1 times and try 

- sudo service terrariumpi stop
- remove the old database. 
- run the installer once more
- reboot

Mi Bluetooth can't work 

![image](https://user-images.githubusercontent.com/74257775/131341503-d23d8479-d2f1-4637-af9c-3262a4680596.png)
![image](https://user-images.githubusercontent.com/74257775/131341881-ab7af576-5404-4d8c-8676-8f85e045de4c.png)

**Comment by theyosh** [comment] 2021-08-30 15:55
But, they are auto detected? So that is part 1. They are found. So we know that Bluetooth should work. At least the hardware is working.

But then it is strange that it does not update. I have one user that said it worked.... so now we have to figure out why it does not work for you. And the hard part is that I do not own this kind device.

So I can add some debug information in the code, but that also makes it that you need it to run the software manual. So we can see what is going on. If you have some time, we can try this.

**Comment by captainboto** [comment] 2021-08-30 16:02
@theyosh  they not auto detected but i try scan on raspberrypi Bluetooth is working and saw Mac Address so maybe is they are difference hardware mine is **xiaomi Mijia Product model: LYWSD03MMC**  and I search issue found one #335 is **Product model: LYWSDCGQ/01ZM**

**Comment by theyosh** [comment] 2021-08-30 16:44
Ok, I added some debug code so we can see if we can figure out why it is not working.

So follow these steps:
1. stop terrariumpi: `sudo service terrariumpi stop`
2. go to the code directory: `cd /home/pi/TerrariumPI`
3. update the code: `git pull`
4. load python environment: `source venv/bin/activate`
5. run the software by hand: `python terrariumPI.py`

Now the software should startup. And when you see the line:
```
2021-08-30 17:32:39,000 - INFO    - terrariumWebserver   - Running webserver at 0.0.0.0:8090
```

You know it is loaded. Before that line, there should be some lines about bluetooth. You can select all the text in the console and past it here in a code block. Or attach as a text file.

**Comment by captainboto** [comment] 2021-08-30 16:47
Ok, i do it code show like this 

(venv) pi@raspberrypi:~/TerrariumPI $ python terrariumPI.py
2021-08-30 23:46:56,068 - INFO    - terrariumEngine      - Starting TerrariumPI 4.0.0 ...
2021-08-30 23:46:56,133 - INFO    - terrariumEngine      - Loaded 28 settings in 0.06 seconds.
2021-08-30 23:46:56,559 - INFO    - terrariumEngine      - Loading existing sensors from database.
2021-08-30 23:46:56,605 - INFO    - terrariumEngine      - Loaded sensor bme280 humidity named 'BME280-Humidity' at address '76' with value 100.00% in 0.04 seconds.
2021-08-30 23:46:56,608 - INFO    - terrariumEngine      - Loaded sensor bme280 temperature named 'BME280-Temp' at address '76' with value 18.98C in 0.00 seconds.
2021-08-30 23:46:56,610 - INFO    - terrariumEngine      - Scanning for new sensors ...
Scanning bluetooth for: <class 'hardware.sensor.miflora_sensor.terrariumMiFloraSensor'>
Found bluetooth device:
None
Found bluetooth device:
None
Found bluetooth device:
None
Found bluetooth device:
None
Found bluetooth device:
None
Found bluetooth device:
None
Found bluetooth device:
None
Found bluetooth device:
MiKettle
Found bluetooth device:
None
Found bluetooth device:
White_D239736C16E2
Found bluetooth device:
None
Found bluetooth device:
None
Found bluetooth device:
None
Found bluetooth device:
None
Found bluetooth device:
LYWSD03MMC
Scanning bluetooth for: <class 'hardware.sensor.mitemp_sensor.terrariumMiTempSensor'>
Found bluetooth device:
None

**Comment by captainboto** [comment] 2021-08-30 17:10
i try terminal scan and pair got message **Failed to pair: org.bluez.Error.AuthenticationFailed**
![image](https://user-images.githubusercontent.com/74257775/131377562-4cb63f37-d482-4849-a785-c3d47ebdc9fa.png)

**Comment by theyosh** [comment] 2021-08-30 17:16
Thanks for the log. I guess `LYWSD03MMC` is the sensor. But the problem is that is not a supported sensor.

For mi-temp I expect a different name, so I guess I cannot support those. 

Also, when you added it manually, it still does not update. You have added it correctly. So even when I did not find during auto scanning because of the name, it still does not work.
As far I can judge now, it fails when it loads the battery level. This is inside the mitemp-bt module that I use. So that is something I cannot fix.

Is this Bluetooth sensor a V1 version? How old is it? And did you run TP3 also with this sensor? Because I am getting at a point that I do not have any options left to test.

**Comment by captainboto** [comment] 2021-08-30 17:24
this Sensor is V2 same 3 of them https://github.com/theyosh/TerrariumPI/issues/335#issuecomment-683771694 
Hmm, #https://github.com/ratcashdev/mitemp#mitemp_bt---library-for-xiaomi-mi-temperature-and-humidity-sensor-v2-with-bleutooth-le-and-the-lcd-display I check this and they should work. I don't run TP3 with this Sensor before just try in TP4 

i can connect Sensor. but TP4 can't read data right?
![image](https://user-images.githubusercontent.com/74257775/131378411-fe3f3fba-c165-4143-bb0d-49b6acb94b93.png)

**Comment by theyosh** [comment] 2021-08-30 17:26
> i try terminal scan and pair got message **Failed to pair: org.bluez.Error.AuthenticationFailed**
> ![image](https://user-images.githubusercontent.com/74257775/131377562-4cb63f37-d482-4849-a785-c3d47ebdc9fa.png)

That could also be a RPI issue. Also, I do not know if the sensor can handle multiple connections. If my software is still running, it will try to connect. And if you also try to do that, I do not know what happens.

Also, sometimes Bluetooth got stuck. And than a bluetooth service restart could fix it: `sudo service bluetooth restart`

**Comment by captainboto** [comment] 2021-08-30 17:38
try sudo service bluetooth restart and got this message can't pair but can connected 

![image](https://user-images.githubusercontent.com/74257775/131381043-e0a47882-dc4f-4260-b0d4-4ed8ecc7bb1f.png)
![image](https://user-images.githubusercontent.com/74257775/131381080-fe8f4541-1ff2-4a10-b59c-62dbfa679f7b.png)

**Comment by theyosh** [comment] 2021-08-30 17:50
Hmm, not sure, but I found https://github.com/JsBergbau/MiTemperature2 which is mention `LYWSD03MMC` explicit. But it also says it is version 2. But then again, it is Chinese stuff... not sure how strict they are with their hardware.
But it looks like there is a difference. Because again, you added it manual, and still my software was not able to read out the values.

So at this point, I am afraid, that somehow you should be able to get the device connected with the RPI using Python. And this should be done without my software running. If that works, then we know that we can connect and read out the sensor.

So, for now we can conclude that:
1. Bluetooth scanning is working correctly. Therefore the installation is also correctly.
2. The sensor looks unsupported now.

**Comment by captainboto** [comment] 2021-08-30 17:56
Im done with this sensor i will get back to make 2 I2C connect with BME280 from Sparkfun

So Thank a lot 😉

**Comment by theyosh** [comment] 2021-09-01 19:39
Ok, can we close this issue regarding the Mi-Temp Bluetooth device? And open a new one for other issues?

**Comment by theyosh** [comment] 2021-09-08 19:07
Hi, apparently there are different MiTemp devices. As https://github.com/theyosh/TerrariumPI/issues/604#issuecomment-914638684 managed to add 2 sensors.

So, this is really stupid, and I do now know how to fix that. Only solution is to buy a new one and hope it will work.... but that is taking a gamble.

**Closed by theyosh** 2021-09-08 19:07 UTC

**Comment by cnelsonsic** [comment] 2021-12-19 05:06
I took a gamble, bought 4 and got annoyed that they didn't work out of the box so I'm working on adding these.

**Comment by theyosh** [comment] 2021-12-25 18:00
In both `main` and `4.x.y.z` branch have now support for these sensors. Do a `git pull` and rerun the installer. They should then be automatically found during startup.
