### ISSUE TITLE
[BUG]: Enclosure - Area settings button disappears from screen and small typo

### ISSUE THREAD

**Issue by Dragonfly-terra** [theyosh/TerrariumPI#717] opened 2022-06-30 19:38 UTC
**Setup:**
 - TerrariumPI version: 4.3.3 [main]
 - Python version: 3
 - Raspberry PI: 4
 - Webbrowser: Opera GX version LVL 4 (core: 88.0.4412.65)

**Describe the bug**
Display of the settings button disappears add the enclosures list.
Small typo in the Area settings Dimmer. Dimmer **of** duration should be Dimmer **off** duration

**To Reproduce / Installation steps**
Setting up a light with day and night timing. Long text resulting in disappearing of the settings button.
Add a Area with a Dimmer.

**Expected behavior**
Perhaps a Night settings could be placed below the Day settings. Or move the settings button before the area settings.

**Screenshots**
![image](https://user-images.githubusercontent.com/64733289/176762580-8a2a5102-91ab-4d66-9af1-cb21ef4056fb.png)
![image](https://user-images.githubusercontent.com/64733289/176762653-90daca4f-46b2-4120-8fc2-53a627a3d423.png)

Thanks for this great software and all your support.

**Comment by theyosh** [comment] 2022-07-02 09:54
Duplicate of #716

**Closed by theyosh** 2022-07-02 09:54 UTC
