### ISSUE TITLE
Water level sensor

### ISSUE THREAD

**Issue by bartch** [theyosh/TerrariumPI#99] opened 2018-02-14 18:44 UTC
Is there a possibility to support water level sensors e.g. for water tanks? If yes, do you have a suggestion?

**Comment by Aapjes94** [comment] 2018-02-14 19:11
Issue #87 addresses this in a way, might be worth checking out.

**Comment by theyosh** [comment] 2018-02-14 20:29
Duplicate of #87

**Closed by theyosh** 2018-02-14 20:29 UTC
