### ISSUE TITLE
[BUG]: V4 Database lock

### ISSUE THREAD

**Issue by chrRtg** [theyosh/TerrariumPI#562] opened 2021-07-08 18:07 UTC
**Setup:**
 - Python version: 3
 - Raspberry PI: 3B

**Describe the bug**

```
TerrariumPI was not booting up. In the syslog I found the following lines:
Jul  8 18:04:15 raspberrypi python[611]:   File "/home/TerrariumPI/venv/lib/python3.7/site-packages/yoyo/backends.py", line 352, in _insert_lock_row
Jul  8 18:04:15 raspberrypi python[611]:     "(run yoyo break-lock to remove this lock)".format(row[0])
```
The full syslog see https://gist.github.com/chrRtg/d1901371de7a64018c339880cb07adeb

While I'm not used to yoyo or such I finally deleted the database file `terrariumpi.db`. After the next restart TerrariumPI came up properly.

I don't know if this is a bug or bad luck which broke the database. Maybe a short help on how to unlock or repair the database in such cases will help.

**Comment by theyosh** [comment] 2021-07-09 11:50
HI thanks for the issue,

I am a bit new to the yoyo package. It looked a nice DB migration package. So I have seen this issue myself, but I did not much investigating about this. As you also noticed, removing the terrariumpi.db and restart will fix it.

And when I remove my db and restart, it always works. So could it be that this has happened just right after the install? And where the installer is asking for a reboot?
Because I have 1 idea:
When you (re)start a Pi, I noticed that the clock is off. And it takes some time before the Pi syncs it time. And I have a watchdog for the terrariumpi service, which will restart if the startup does not take place in 2 minutes. So I do not know what happens when you boot your pi, which is 10 min behind, start my software, updates the clock and jumps 10 min. And maybe this will trigger the watchdog to restart my software. And that will make a second start, and then you get these DB locking errors.

Once you are running, and remove the db and start over, there is no time syncing issue, and no extra restart of my software... But this is a guess.. hard to test.

**Comment by chrRtg** [comment] 2021-07-09 16:41
Then it's an issue which may happen only on install because this yoyo is only used for a migration?

I understand TerraiumPI is a service. Then it should be stopped before a shutdown or reboot. Maybe the order is wrong, first stop watchdog, then TerrariumPI?

**Comment by theyosh** [comment] 2021-07-13 07:54
I have done some testing, and I can't reproduce. But for now, this only happens on an clean install. Then deleting the DB is the easiest thing to do. As there is no data in it, you delete the DB and let the software recreate.

I think this will be a FAQ entry.

**Comment by theyosh** [comment] 2021-07-19 13:16
Closing now. Will add it to the FAQ when final version is released.

**Closed by theyosh** 2021-07-19 13:16 UTC
